export const airports = [
  { value: "", label: "All Airports" },
  { value: "ACA", label: "General Juan N. Álvarez International Airport" },
  { value: "AGU", label: "Jesús Terán Peredo International Airport (AGU) " },
  { value: "MMAL", label: "Agualeguas National Airport" },
  { value: "XAL", label: "Álamos National Airport" },
  { value: "AZG", label: "Pablo L Sidar National Airport" },
  { value: "AZP", label: "Jorge Jiménez Cantú National Airport" },
  { value: "MMSL", label: "Cabo San Lucas International Airport" },
  { value: "CPE", label: "Ing. Alberto Acuña Ongay International Airport" },
  { value: "CNA", label: "Cananea National Airport" },
  { value: "CUN", label: "Cancún International Airport (CUN)" },
  { value: "MMCD", label: "Isla de Cedros Airport" },
  { value: "CYW", label: "Captain Rogelio Castillo National Airport" },
  { value: "CTM", label: "Chetumal International Airport" },
  { value: "CZA", label: "Chichen Itza International Airport" },
  {
    value: "CUU",
    label: "General Roberto Fierro Villalobos International Airport (CUU)",
  },
  { value: "MMCH", label: "Chilpancingo National Airport" },
  { value: "ACN", label: "Ciudad Acuña International Airport" },
  //   { value: "#", label: "Santa Barbara Regional Airport" },
  { value: "CUA", label: "Ciudad Constitución Airport" },
  { value: "CME", label: "Ciudad del Carmen International Airport (CME)" },
  { value: "MMC", label: "Ciudad Mante National Airport" },
  { value: "CJS", label: "Abraham González International Airport (CJS)" },
  { value: "CEN", label: "Ciudad Obregón International Airport (CEN)" },
  {
    value: "CVM",
    label: "General Pedro J. Méndez International Airport (CVM)",
  },
  { value: "CLQ", label: "Lic. Miguel de la Madrid Airport (CLQ)" },
  { value: "CJT", label: "Copalar Air Force Base Num 17" },
  { value: "CZM", label: "Cozumel International Airport" },
  { value: "CVJ", label: "General Mariano Matamoros Airport (CVJ)" },
  { value: "CUL", label: "Culiacán International Airport (CUL)" },
  { value: "MM29", label: "Aeropuerto Nacional Ta Lo De Soto" },
  {
    value: "DGO",
    label: "General Guadalupe Victoria International Airport (DGO)",
  },
  { value: "ESE", label: "El Ciprés Air Force Base Num 3" },
  {
    value: "GDL",
    label: "Don Miguel Hidalgo y Costilla International Airport (GDL)",
  },
  //   { value: "#", label: "Campo Cuatro Milpas Airport" },
  { value: "GYM", label: "General José María Yáñez International Airport" },
  { value: "GUB", label: "Guerrero Negro Airport" },
  {
    value: "HMO",
    label: "General Ignacio Pesqueira Garcia International Airport",
  },
  { value: "HUX", label: "Bahías de Huatulco International Airport (HUX)" },
  { value: "MMGD", label: "Isla Guadalupe Airport" },
  { value: "MX-0038", label: "Isla María Madre Naval Air Station" },
  { value: "ISJ", label: "Isla Mujeres National Airport" },
  { value: "ZIH", label: "Ixtapa-Zihuatanejo International Airport" },
  { value: "IZT", label: "Ixtepec Airport" },
  { value: "LAP", label: "Manuel Márquez de León International Airport" },
  { value: "LOM", label: "Francisco Primo de Verdad National Airport" },
  { value: "LZC", label: "Lázaro Cárdenas Airport " },
  { value: "BJX", label: "Del Bajío International Airport (BJX) " },
  { value: "LTO", label: "Loreto International Airport (LTO)" },
  { value: "SJD", label: "Los Cabos International Airport" },
  {
    value: "LMM",
    label: "Federal del Valle del Fuerte International Airport (LMM)",
  },
  { value: "ZLO", label: "Playa de Oro International Airport" },
  { value: "MAM", label: "General Servando Canales International Airport" },
  { value: "MM67", label: "Manuel Moreno Torres National Airport" },
  { value: "MZT", label: "General Rafael Buelna International Airport (MZT)" },
  { value: "MID", label: "Merida International Airport (MID)" },
  {
    value: "MXL",
    label: "General Rodolfo Sánchez Taboada International Airport",
  },
  { value: "MEX", label: "Aeropuerto Internacional Benito Juárez (MEX)" },
  { value: "MTT", label: "Minatitlán/Coatzacoalcos National Airport" },
  { value: "LOV", label: "Venustiano Carranza International Airport (LOV)" },
  {
    value: "MTY",
    label: "General Mariano Escobedo International Airport (MTY)",
  },
  { value: "NTR", label: "Del Norte International Airport" },
  {
    value: "MLM",
    label: "General Francisco J. Mujica International Airport (MLM)",
  },
  { value: "MUG", label: "Mulegé National Airport" },
  { value: "NVJ", label: "Navojoa Airport" },
  { value: "NOG", label: "Nogales International Airport (NOG)" },
  { value: "NCG", label: "Nuevo Casas Grandes Municipal Airport" },
  { value: "NLD", label: "Quetzalcóatl International Airport (NLD)" },
  { value: "OAX", label: "Oaxaca International Airport (OAX)" },
  { value: "MMPC", label: "Ing. Juan Guillermo Villasana National Airport" },
  { value: "PQM", label: "Palenque International Airport (PQM)" },
  {
    value: "MMPD",
    label: "León Gonzalez Pie de la Cuesta Air Force Base Num 7",
  },

  { value: "PCM", label: "Playa del Carmen National Airport" },
  { value: "PDS", label: "Piedras Negras International Airport (PDS)" },
  { value: "PAZ", label: "El Tajín National Airport (PAZ)" },
  { value: "PBC", label: "Puebla International Airport (PBC)" },
  { value: "PXM", label: "Puerto Escondido International Airport (PXM)" },
  { value: "PPE", label: "Puerto Peñasco International Airport" },
  {
    value: "PVR",
    label: "Lic. Gustavo Díaz Ordaz International Airport (PVR)",
  },
  { value: "QRO", label: "Querétaro International Airport (QRO)" },
  { value: "REX", label: "General Lucio Blanco International Airport (REX)" },
  { value: "SCX", label: "Salina Cruz Naval Air Station" },
  { value: "SLW", label: "Plan de Guadalupe International Airport (SLW)" },
  { value: "SFH", label: "San Felipe International Airport" },
  { value: "SLP", label: "San Luis Potosí International Airport (SLP)" },
  { value: "UAC", label: "San Luis Río Colorado Airport" },
  { value: "NLU", label: "Santa Lucía Air Force Base Num 1" },
  { value: "SRL", label: "Palo Verde Airport" },
  {
    value: "TAM",
    label: "General Francisco Javier Mina International Airport",
  },
  { value: "TSL", label: "Tamuín National Airport" },
  { value: "TAP", label: "Tapachula International Airport" },
  { value: "MX-0433", label: "Teacapan Naval Air Station" },
  { value: "TCN", label: "Tehuacán National Airport" },
  { value: "TPQ", label: "Amado Nervo National Airport (TPQ)" },
  {
    value: "TIJ",
    label: "General Abelardo L. Rodríguez International Airport (TIJ)",
  },
  { value: "TZM", label: "Cupul National Airport" },
  {
    value: "TLC",
    label: "Lic. Adolfo López Mateos International Airport (TLC)",
  },
  { value: "TRC", label: "Francisco Sarabia International Airport (TRC)" },
  { value: "TUY", label: "Tulum Naval Air Station " },
  { value: "MMTX", label: "Zapotiltic National Airport" },
  { value: "TGZ", label: "Angel Albino Corzo International Airport (TGZ)" },
  { value: "UPN", label: "Uruapan International Airport (UPN)" },
  { value: "VER", label: "General Heriberto Jara International Airport (VER)" },
  { value: "VSA", label: "Carlos Rovirosa Pérez International Airport (VSA)" },
  { value: "JAL", label: "El Lencero Airport (JAL)" },
  { value: "ZCL", label: "Leobardo C. Ruiz International Airport (ZCL)" },
  { value: "ZMM", label: "Zamora National Airport" },
  { value: "MMZP", label: "Zapopan Air Force Base Num 5 " },
];
